export const FRONTEND_SLIDER_REQUEST = 'FRONTEND_SLIDER_REQUEST'
export const FRONTEND_SLIDER_SUCCESS = 'FRONTEND_SLIDER_SUCCESS'
export const FRONTEND_SLIDER_FAIL = 'FRONTEND_SLIDER_FAIL'

export const ADMIN_SLIDER_REQUEST = 'ADMIN_SLIDER_REQUEST'
export const ADMIN_SLIDER_SUCCESS = 'ADMIN_SLIDER_SUCCESS'
export const ADMIN_SLIDER_FAIL = 'ADMIN_SLIDER_FAIL'

export const CREATE_SLIDER_REQUEST = 'CREATE_SLIDER_REQUEST'
export const CREATE_SLIDER_SUCCESS = 'CREATE_SLIDER_SUCCESS'
export const CREATE_SLIDER_RESET = 'CREATE_SLIDER_RESET'
export const CREATE_SLIDER_FAIL = 'CREATE_SLIDER_FAIL'

export const UPDATE_SLIDER_REQUEST = 'UPDATE_SLIDER_REQUEST'
export const UPDATE_SLIDER_SUCCESS = 'UPDATE_SLIDER_SUCCESS'
export const UPDATE_SLIDER_RESET = 'UPDATE_SLIDER_RESET'
export const UPDATE_SLIDER_FAIL = 'UPDATE_SLIDER_FAIL'

export const DELETE_SLIDER_REQUEST = 'DELETE_SLIDER_REQUEST'
export const DELETE_SLIDER_SUCCESS = 'DELETE_SLIDER_SUCCESS'
export const DELETE_SLIDER_RESET = 'DELETE_SLIDER_RESET'
export const DELETE_SLIDER_FAIL = 'DELETE_SLIDER_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'